// <----------------------- USER AUTHENTICATION ----------->
export const OPEN_AUTH_MODAL = 'OPEN_AUTH_MODAL';
export const CLOSE_AUTH_MODAL = 'CLOSE_AUTH_MODAL';
export const USER_SIGNUP_INITIATE = 'USER_SIGNUP_INITIATE';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNIN_INITIATE = 'USER_SIGNIN_INITIATE';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNOUT = 'USER_SIGNOUT';
export const USER_SIGNOUT_SUCCESS = 'USER_SIGNOUT_SUCCESS';
export const AUTHENTICATE_USER_START = 'AUTHENTICATE_USER_START';
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER';
export const AUTHENTICATE_USER_FAIL = 'AUTHENTICATE_USER_FAIL';
// <----------------------- USER AUTHENTICATION ----------->
export const AUTHENTICATE_USER_GOOGLE_START = 'AUTHENTICATE_USER_GOOGLE_START';
export const AUTHENTICATE_USER_GOOGLE_SUCCESS = 'AUTHENTICATE_USER_GOOGLE_SUCCESS';
// <----------------------- USER EMAIL VERIFICATION ----------->
export const EMAIL_VERIFICATION_INIT = 'EMAIL_VERIFICATION_INIT';
export const EMAIL_VERIFICATION_SUCCESS = 'EMAIL_VERIFICATION_SUCCESS';
export const EMAIL_VERIFICATION_FAILED = 'EMAIL_VERIFICATION_FAILED';
export const REDIRECT_USER = 'REDIRECT_USER';

// <----------------------- FORGOTPASSWORD ----------->
export const FORGOT_PASSWORD_REQUEST_INIT = 'FORGOT_PASSWORD_REQUEST_INIT';

// <----------------------- PRODUCT ----------->
export const OPEN_PRODUCT_MODAL = 'OPEN_PRODUCT_MODAL';
export const CLOSE_PRODUCT_MODAL = 'CLOSE_PRODUCT_MODAL';
export const ADD_NEW_PRODUCT_START = 'ADD_NEW_PRODUCT_START';
export const ADD_NEW_PRODUCT_SUCCESS = 'ADD_NEW_PRODUCT_SUCCESS';
export const EDIT_PRODUCT_START = 'EDIT_PRODUCT_START';
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';
export const FETCH_ALLPRODUCT_START = 'FETCH_ALLPRODUCT_START';
export const FETCH_ALLPRODUCT_SUCCESS = 'FETCH_ALLPRODUCT_SUCCESS';
export const FETCH_ALLPRODUCT_FAILED = 'FETCH_ALLPRODUCT_SUCCESS';
export const FETCH_SINGLE_PRODUCT_START = 'FETCH_SINGLE_PRODUCT_START';
export const FETCH_SINGLE_PRODUCT_SUCCESS = 'FETCH_SINGLE_PRODUCT_SUCCESS';
export const DELETE_SINGLE_PRODUCT_START = 'DELETE_SINGLE_PRODUCT_START';
export const DELETE_SINGLE_PRODUCT_SUCCESS = 'DELETE_SINGLE_PRODUCT_SUCCESS';
export const DELETE_ALL_PRODUCT_START = 'DELETE_ALL_PRODUCT_START';
export const DELETE_ALL_PRODUCT_SUCCESS = 'DELETE_ALL_PRODUCT_SUCCESS';
export const RESET_PRODUCT = 'RESET_PRODUCT';

// <----------------------- TOASTER ----------->
export const MOUNT_TOASTER = 'MOUNT_TOASTER';
export const UNMOUNT_TOASTER = 'UNMOUNT_TOASTER';

// <----------------------- CATEGORY ----------->
export const FETCH_ALL_CATEGORY = 'FETCH_ALL_CATEGORY';
export const FETCH_ALL_CATEGORY_SUCESS = 'FETCH_ALL_CATEGORY_SUCESS';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_SUCCESS';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const REMOVE_CATEGORY_SUCCESS = 'REMOVE_CATEGORY_SUCCESS';
export const OPEN_CATEGORY_MODAL = 'OPEN_CATEGORY_MODAL';
export const CLOSE_CATEGORY_MODAL = 'CLOSE_CATEGORY_MODAL';
export const RESET_CATEGORY = 'RESET_CATEGORY';

// <----------------------- CART ----------->
export const INIT_CART = 'INIT_CART';
export const INIT_CART_SUCCESS = 'INIT_CART_SUCCESS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADDED_TO_CART = 'ADDED_TO_CART';
export const REMOVE_FORM_CART = 'REMOVE_FORM_CART';
export const REMOVE_FORM_CART_SUCCESS = 'REMOVE_FORM_CART_SUCCESS';

// <----------------------- CART ----------->
export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const CANCEL_ORDER = 'CANCEL_ORDER';
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS';

// <----------------------- USER ORDERS ----------->
export const USER_ORDER_REQUEST_INIT = 'USER_ORDER_REQUEST_INIT';
export const USER_ORDER_REQUEST_SUCCESS = 'USER_ORDER_REQUEST_SUCCESS';
export const USER_ORDER_REQUEST_FAILED = 'USER_ORDER_REQUEST_FAILED';

// <----------------------- ADMIN ORDERS ----------->
export const FETCH_ALL_USER_ORDER_INIT = 'FETCH_ALL_USER_ORDER_INIT';
export const FETCH_ALL_USER_ORDER_SUCCESS = 'FETCH_ALL_USER_ORDER_SUCCESS';
export const FETCH_ALL_USER_ORDER_ERROR = 'FETCH_ALL_USER_ORDER_ERROR';
export const UPDATE_ORDER_STATUS_INIT = 'UPDATE_ORDER_STATUS_INIT';
export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS';
export const UPDATE_ORDER_STATUS_FAILED = 'UPDATE_ORDER_STATUS_FAILED';

// <----------------------- USERS ----------->
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
