// <----------------------- USER AUTHENTICATION ----------->
export const OPEN_AUTH_MODAL = "OPEN_AUTH_MODAL"
export const CLOSE_AUTH_MODAL = "CLOSE_AUTH_MODAL"
export const USER_SIGNUP_INITIATE = "USER_SIGNUP_INITIATE"
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS"
export const USER_SIGNIN_INITIATE = "USER_SIGNIN_INITIATE"
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS"
export const USER_SIGNOUT = "USER_SIGNOUT"
export const USER_SIGNOUT_SUCCESS = "USER_SIGNOUT_SUCCESS"
export const AUTHENTICATE_USER_START="AUTHENTICATE_USER_START"
export const AUTHENTICATE_USER_SUCCESS = "AUTHENTICATE_USER"
export const AUTHENTICATE_USER_FAIL = "AUTHENTICATE_USER_FAIL"

// <----------------------- PRODUCT ----------->
export const OPEN_PRODUCT_MODAL = "OPEN_PRODUCT_MODAL"
export const CLOSE_PRODUCT_MODAL = "CLOSE_PRODUCT_MODAL"
export const ADD_NEW_PRODUCT_START = "ADD_NEW_PRODUCT_START"
export const ADD_NEW_PRODUCT_SUCCESS = "ADD_NEW_PRODUCT_SUCCESS"
export const EDIT_PRODUCT_START = "EDIT_PRODUCT_START"
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS"
export const FETCH_ALLPRODUCT_START = "FETCH_ALLPRODUCT_START"
export const FETCH_ALLPRODUCT_SUCCESS = "FETCH_ALLPRODUCT_SUCCESS"
export const FETCH_SINGLE_PRODUCT_START = "FETCH_SINGLE_PRODUCT_START"
export const FETCH_SINGLE_PRODUCT_SUCCESS = "FETCH_SINGLE_PRODUCT_SUCCESS"
export const DELETE_SINGLE_PRODUCT_START="DELETE_SINGLE_PRODUCT_START"
export const DELETE_SINGLE_PRODUCT_SUCCESS="DELETE_SINGLE_PRODUCT_SUCCESS"
export const DELETE_ALL_PRODUCT_START="DELETE_ALL_PRODUCT_START"
export const DELETE_ALL_PRODUCT_SUCCESS="DELETE_ALL_PRODUCT_SUCCESS"

// <----------------------- TOASTER ----------->
export const MOUNT_TOASTER="MOUNT_TOASTER"
export const UNMOUNT_TOASTER="UNMOUNT_TOASTER"



